spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhihu?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Wr020614
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 开发环境自动建表
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  elasticsearch:
    hosts: http://localhost:9200
    connection-timeout: 1000
    socket-timeout: 30000
    # username: elastic
    # password: ThYQBHOh_PpImJ*2IDiF